### ISSUE TITLE
Testing mode

### ISSUE THREAD

**Issue by MrS1lentcz** [ImaginaryLandscape/django-nocaptcha-recaptcha#4]
Could be very useful to mention in readme file an example, how to use this library in integration tests
The right settings is:

test setUp:
os.environ['NORECAPTCHA_TESTING'] = 'True'

POST data:
'g-recaptcha-response: 'PASSED'

...raises ValidationError otherwise

**Comment by torstenrudolf** [comment]
Hey @MrS1lentcz did you integrate e2e tests (e.g. via selenium) with django-nocaptcha-recaptcha ?
I'm struggling in understanding how to implement a selenium test.
How do you set the value to 'PASSED' in the post data? 
Even if I follow the [google instructions](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-test-with-recaptcha-v2-how-should-i-do) the value of the field is still an empty string.

Furthermore, shouldn't the `NORECAPTCHA_TESTING` variable rather be a setting than an os environ variable?

**Comment by ffuentese** [comment]
I tried making tests with that variable but it doesn't work (in some sense it makes sense that it doesn't). You can make functional tests where you can pass the g-recaptcha-response. In a Selenium test you don't (or at least you shouldn't).
