### ISSUE TITLE
Django 2 compatibility

### ISSUE THREAD

**Issue by diolk49** [ImaginaryLandscape/django-nocaptcha-recaptcha#8]
Hi,
I found a problem in this file
```
  File "/.../lib/python3.6/site-packages/nocaptcha_recaptcha/client.py", line 8, in <module>
    from django.utils import simplejson as json

```
This is trying to import simplejson (not available since Django 1.5) instead of json package, because of this test, that checks Django only checks the subversion : 

```
if django.VERSION[1] >= 5:
    import json
else:
    from django.utils import simplejson as json
```
By replacing the first line with this, this is ok :
`if django.VERSION[1] >= 5 or django.VERSION[0] > 1:`

Please update it, that would be great :)

Thanks, 
Louison

**Comment by JoeJasinski** [comment]
I haven't tested for django 2.0 specifically, but the import issue should be resolved now, per version 0.0.20.
